### ISSUE TITLE
群主功德无量，k8s系列良心书籍，比阿里京东那些复制粘贴刷名气，昧着良心写书评的书强100倍

### ISSUE THREAD

**Issue by tx991020** [mgxian/istio-lab#1]
群主功德无量，k8s系列良心书籍，比阿里京东那些复制粘贴刷名气，昧着良心写书评的书强100倍，全书没一句废话，全实战，希望建个qq群

**Comment by mgxian** [comment]
感谢支持 感谢你的建议 群已经创建好了 欢迎加入 747894051
